import { createApp } from 'vue/dist/vue.esm-bundler.js';
import './style.css';
import JourneyScene from './JourneyScene.js';
import GardenShop from './GardenShop.js';
import RecipeBook from './RecipeBook.js';

createApp({
  components: { JourneyScene, GardenShop, RecipeBook },
  data: () => ({ shopRequests: {}, notice: '', username: '', password: '', authMode: 'login', claimLegacy: false, tick: 0, state: null, page: 'home', kind: 'frog', name: '', place: 'forest', food: 'rice_ball', tool: '', giftTo: '', giftItem: '', busy: false, error: '', selected: null, now: Date.now()/1000, offset: 0, timer: null, polling: false, refreshTask: null,
    animals: {frog:'🐸',cat:'🐱',fox:'🦊',rabbit:'🐰',squirrel:'🐿️'}, labels:{frog:'青蛙',cat:'小猫',fox:'狐狸',rabbit:'兔子',squirrel:'松鼠'},
  }),
  computed: {
    places(){return this.state?.catalog?.places || {};},
    recipes(){return this.state?.catalog?.combinations || [];},
    placeRecipes(){return this.recipes.filter(r=>r.place===this.place);},
    pairing(){return this.placeRecipes.filter(r=>r.food===this.food&&(!r.tool||r.tool===this.tool)).sort((a,b)=>Number(!!b.tool)-Number(!!a.tool))[0];},
    garden(){return this.state?.garden;},
    gardenReady(){return this.garden?.plots.filter(p=>p.ready_at!==null&&p.ready_at<=this.now).length || 0;},
    animal(){ return this.state?.animal; },
    trip(){return this.state?.travel;},
    cards(){return this.state?.postcards || [];},
    unread(){return this.cards.filter(c=>!c.opened);},
    inventory(){return this.state?.inventory || {foods:[],tools:[],souvenirs:[],daily:{available:false,item:{}}};},
    gifts(){return this.state?.gifts || [];},
    giftableSouvenirs(){return this.inventory.souvenirs.filter(item=>item.quantity>0);},
    selectedFood(){return this.inventory.foods.find(item=>item.key===this.food) || this.inventory.foods.find(item=>item.quantity>0);},
    foodCount(){return this.inventory.foods.reduce((sum,item)=>sum+item.quantity,0);},
    canDepart(){return !this.busy && !this.trip && !!this.selectedFood && this.selectedFood.quantity>0;},
    canGift(){return !this.busy && !!this.giftTo && !!this.giftItem && this.giftableSouvenirs.some(item=>item.key===this.giftItem);},
    remaining(){return Math.max(0, Math.ceil((this.trip?.ends_at || 0)-this.now));},
    progress(){return this.trip ? Math.min(100,Math.max(0,(this.now-this.trip.started_at)/(this.trip.ends_at-this.trip.started_at)*100)):0;}
  },
  methods: {
    async api(path, body){
      const response = await fetch('/api'+path, body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
      if(response.status===401 && path!=='/login'){this.selected=null;this.state=null; await this.refresh();}
      if(!response.ok){const e=await response.json().catch(()=>({}));throw new Error(typeof e.detail==='string'?e.detail:'操作没有完成，请稍后重试。');}
      return response.json();
    },
    async refresh(){
      if(this.refreshTask)return this.refreshTask;
      this.polling=true;
      this.refreshTask=(async()=>{
        try{this.state=await this.api('/state');this.offset=this.state.server_time-Date.now()/1000;this.now=this.state.server_time;this.error='';this.syncPacking();}
        catch(e){this.error='暂时连接不上小屋，请检查服务是否启动，再点击重试。';}
      })();
      try{await this.refreshTask;}finally{this.polling=false;this.refreshTask=null;}
    },
    async act(path,body,after){
      if(this.busy)return;
      this.busy=true;this.error='';
      try{if(this.refreshTask)await this.refreshTask;await this.api(path,body);await this.refresh();after?.();}
      catch(e){this.error=e.message;}finally{this.busy=false;}
    },
    authenticate(){this.act('/'+(this.authMode==='login'?'login':'register'),{username:this.username,password:this.password,claim_legacy:this.claimLegacy},()=>{this.password='';this.page='home';});},
    logout(){this.act('/logout',{},()=>{this.selected=null;this.password='';this.page='home';});},
    clock(t){return new Date(t*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});},
    adopt(){this.act('/animal',{kind:this.kind,name:this.name});},
    syncPacking(){const foods=this.state?.inventory?.foods || [];const ownedFood=foods.find(item=>item.key===this.food) || foods.find(item=>item.quantity>0);if(ownedFood)this.food=ownedFood.key;const tools=this.state?.inventory?.tools || [];if(this.tool&&!tools.find(item=>item.key===this.tool&&item.quantity>0))this.tool='';const friends=this.state?.friends || [];if(this.giftTo&&!friends.find(friend=>friend.username===this.giftTo))this.giftTo='';if(!this.giftTo&&friends.length)this.giftTo=friends[0].username;const gift=this.giftableSouvenirs.find(item=>item.key===this.giftItem) || this.giftableSouvenirs[0];this.giftItem=gift?.key || '';},
    depart(){this.act('/travel',{place:this.place,food:this.food,tool:this.tool||null},()=>this.page='home');},
    claimDaily(){this.act('/inventory/daily',{});},
    plant(plot){this.act('/garden/'+plot+'/plant',{},()=>this.notice='种好了！三叶草会慢慢长大，离线也没关系。');},
    harvest(plot){this.act('/garden/'+plot+'/harvest',{},()=>this.notice='收获了 '+this.garden.harvest_amount+' 三叶草，去挑一份点心吧。');},
    buy(item){const request_id=this.shopRequests[item] ||= crypto.randomUUID();this.act('/shop/buy',{item,request_id},()=>{delete this.shopRequests[item];this.notice='兑换成功，食物已经放进背包。';});},
    prepareRecipe(recipe){this.place=recipe.place;this.food=recipe.food;this.tool=recipe.tool||'';this.page='prepare';this.notice='已选好「'+recipe.title+'」的搭配。';this.$nextTick(()=>document.getElementById('packing')?.scrollIntoView({block:'start'}));},
    itemName(key){return [...this.inventory.foods,...this.inventory.tools,...this.inventory.souvenirs].find(i=>i.key===key)?.name || key;},
    sendGift(){this.act('/gifts',{to_username:this.giftTo,item:this.giftItem});},
    open(card){this.selected=card;if(!card.opened)this.act('/postcards/'+card.id+'/open',{});},
    date(t){return new Date(t*1000).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'});},
    rewardText(card){return card.rewards?.length?card.rewards.map(item=>item.icon+' '+item.name).join('、'):card.gift;},
    escape(e){if(e.key==='Escape')this.selected=null;}
  },
  async mounted(){await this.refresh();this.timer=setInterval(()=>{this.now=Date.now()/1000+this.offset;this.tick++;if(!this.busy&&((this.trip&&this.remaining===0)||(this.state?.user&&this.tick%10===0)))this.refresh();},1000);document.addEventListener('keydown',this.escape);},
  beforeUnmount(){clearInterval(this.timer);document.removeEventListener('keydown',this.escape);},
  template: `
    <div class="shell">
      <header><a class="brand" href="#" @click.prevent="page='home'"><span class="brand-mark">✳</span><span>小小远行<small>JustASmallJourney</small></span></a><span class="header-note">把日子过慢一点，把世界看多一点。</span><span class="account" v-if="state?.user">{{state.user.username}} <button class="text-button" @click="logout" :disabled="busy">退出</button></span><span class="edition" v-else>草叶与远行 · 07</span></header>
      <div v-if="error" class="error" role="alert">{{error}} <button @click="refresh" :disabled="polling">重试</button></div>
      <div v-if="notice && state?.user" class="pairing-hint" role="status">{{notice}} <button class="text-button" @click="notice=''">收起</button></div>
      <main v-if="!state" class="loading">正在打开你的小屋…</main>
      <main v-else-if="!state.user" class="welcome auth-screen">
        <span class="eyebrow">OUR LITTLE SHARED WORLD</span><h1>世界很大，<br>在这里遇见朋友。</h1><p>每个人一间小屋，每一次远行都有新的故事。<br>登录后，回到属于你的小世界。</p>
        <div class="auth-tabs"><button :class="{active:authMode==='login'}" @click="authMode='login';error=''">回到小屋</button><button :class="{active:authMode==='register'}" @click="authMode='register';error=''">初次入住</button></div>
        <form @submit.prevent="authenticate"><label for="username">用户名</label><input id="username" v-model="username" required maxlength="24" autocomplete="username" placeholder="朋友们怎么称呼你"><label for="password">密码</label><input id="password" type="password" v-model="password" required minlength="8" maxlength="128" :autocomplete="authMode==='login'?'current-password':'new-password'" placeholder="至少 8 位字符">
        <label v-if="authMode==='register'&&state.legacy_available" class="legacy-choice"><input type="checkbox" v-model="claimLegacy" required>将原来的小动物与旅行回忆保存到我的账号</label><button class="primary" :disabled="busy||!username.trim()||password.length<8">{{busy?'正在打开小屋…':authMode==='login'?'登录小屋 ↗':'创建我的账号 ↗'}}</button></form><p class="hint">这个小世界，最多容纳 15 位朋友。</p>
      </main>
      <main v-else-if="!animal" class="welcome">
        <span class="eyebrow">一段小小的故事，从这里开始</span><h1>谁会陪你，<br>走过这些好天气？</h1><p>选一只小动物，为它起个名字。<br>以后，它会把远方的风景带回给你。</p>
        <form @submit.prevent="adopt"><div class="animal-options"><button v-for="(emoji,key) in animals" :key="key" type="button" :class="{chosen:kind===key}" @click="kind=key" :aria-pressed="kind===key"><span>{{emoji}}</span>{{labels[key]}}</button></div><label for="animal-name">它的名字</label><input id="animal-name" v-model="name" maxlength="16" required placeholder="例如：小满" autocomplete="off"><button class="primary" :disabled="busy||!name.trim()">{{busy?'正在布置小屋…':'一起住进小屋 ↗'}}</button></form>
      </main>
      <template v-else>
        <nav aria-label="主要页面"><button :class="{active:page==='home'}" @click="page='home'">⌂ 我的小屋</button><button :class="{active:page==='prepare'}" @click="page='prepare'">♧ 去远行</button><button :class="{active:page==='backpack'}" @click="page='backpack'">▥ 背包 <span>{{foodCount}}</span></button><button :class="{active:page==='collection'}" @click="page='collection'">▤ 明信片 <span>{{cards.length}}</span></button><button :class="{active:page==='world'}" @click="page='world'">♧ 朋友世界</button><button :class="{active:page==='garden'}" @click="page='garden'">☘ 草圃小铺 <span v-if="gardenReady">{{gardenReady}}</span></button></nav>
        <section v-if="state.weather" class="weather-strip" aria-label="小世界今日天气"><span class="weather-icon">{{state.weather.icon}}</span><div><strong>小世界今日 · {{state.weather.name}} · {{state.weather.season.name}}</strong><p>{{state.weather.note}} {{state.weather.season.note}}</p><small>大家共享的天气，每天更新 · {{state.weather.date}}</small><small v-if="trip?.weather">这次出发：{{trip.weather.icon}} {{trip.weather.name}} · {{trip.weather.date}}</small></div></section>
        <main v-if="page==='home'">
          <div class="page-heading"><div><span class="eyebrow">HOME, SWEET HOME</span><h1>{{trip?'它去看看世界了。':'平凡的一天，也有小小期待。'}}</h1><p>{{trip?'你可以先去忙，远方的故事会等你回来。':'收好行囊，让下一段故事慢慢发生。'}}</p></div><span class="status"><i :class="{away:trip}"></i>{{animal.name}} · {{trip?'旅行中':'在家'}}</span></div>
          <section v-if="garden" class="garden-shortcut"><div><strong>☘ 小院草圃 · {{garden.clovers}} 三叶草</strong><p>{{gardenReady?gardenReady+' 块地成熟了，收获后可以兑换食物。':'种一点三叶草，为下一次远行换点新口味。'}}</p></div><button class="primary" @click="page='garden'">{{gardenReady?'去收获 ↗':'照料草圃 ↗'}}</button></section>
          <div class="home-grid"><journey-scene :animal="animals[animal.kind]" :name="animal.name" :away="!!trip" :weather="state.weather" :unread="unread.length" @navigate="page=$event" @mail="unread.length?open(unread[0]):page='collection'" />
          <aside class="home-side"><section class="panel journey-panel"><span class="eyebrow">{{trip?'ON THE ROAD':'NEXT LITTLE ADVENTURE'}}</span><h2>{{trip?places[trip.place].name:'今天，去哪里走走？'}}</h2><p>{{trip?(trip.food?.name||'点心')+'已经带好，小小的冒险正在发生。':'选好食物和小工具，就可以出发了。'}}</p><template v-if="trip"><div class="travel-emoji">{{animals[animal.kind]}} <span>······</span> {{places[trip.place].icon}}</div><div class="progress"><div :style="{width:progress+'%'}"></div></div><div class="countdown">{{remaining>0?'预计 '+remaining+' 秒后回家':'正在整理旅行回忆…'}}</div><p class="hint">{{trip.tool?'带上了'+trip.tool.name+'，也许会有特别发现。':'关掉网页也没关系，旅程会继续。'}}</p></template><template v-else><div class="packed"><span class="packed-icon">{{selectedFood?.icon||'🍙'}}</span><span>{{selectedFood?.name||'饭团'}} · {{selectedFood?.quantity||0}} 份<small>{{inventory.daily.available?'今天还有饭团补给':'今日饭团已领取'}}</small></span></div><div class="quick-actions"><button class="text-button" @click="page='backpack'">查看背包 →</button><button class="text-button" v-if="inventory.daily.available" @click="claimDaily" :disabled="busy">领取今日饭团 →</button></div><button class="primary" @click="page='prepare'">准备一场远行 ↗</button></template></section><section class="mail-panel"><span class="mail-icon">✉</span><div><h3>{{unread.length?'有 '+unread.length+' 张新明信片':'远方来信'}}</h3><p>{{unread.length?'一份小小的惊喜，等你拆开。':'旅行带回的故事，会好好存在这里。'}}</p><button class="text-button" @click="unread.length?open(unread[0]):page='collection'">{{unread.length?'拆开看看 →':'看看收藏 →'}}</button></div></section></aside></div>
          <section class="recent"><div class="section-heading"><h2>留住一些好时光 <span>RECENT MEMORIES</span></h2><button class="text-button" @click="page='collection'">全部明信片 ↗</button></div><div v-if="!cards.length" class="empty-memory">✧ 第一张明信片，会是什么风景呢？ <span>等它旅行回来，这里就有故事了。</span></div><div v-else class="card-grid"><button v-for="card in cards.slice(0,3)" class="postcard" @click="open(card)"><div class="mini-scene" :class="card.place"><span>{{places[card.place].icon}}</span><b v-if="card.participants.length" class="companions"><span v-for="(p,i) in card.participants" :key="i">{{animals[p.kind]}}</span></b><b v-else>{{animals[card.animal]}}</b><i v-if="!card.opened">NEW</i></div><div class="card-meta"><strong>{{card.encounter_id?'同行 · ':''}}{{places[card.place].name}}</strong><span>{{date(card.created_at)}}</span></div></button></div></section>
        </main>
        <main v-else-if="page==='prepare'"><div class="page-heading"><div><span class="eyebrow">A PLACE TO WANDER</span><h1>挑一个心动的远方。</h1><p>不必走得很远，也能带回新的故事。</p></div><span class="edition">每次约 {{state.duration}} 秒</span></div><div class="destinations"><button v-for="(p,key) in places" :class="['destination',key,{chosen:place===key}]" @click="place=key" :aria-pressed="place===key"><div class="destination-art">{{p.icon}}</div><div class="destination-copy"><small>{{p.tag}}</small><h2>{{p.name}} <span v-if="place===key">✓</span></h2><p>{{p.description}}</p></div></button></div><div class="destination-preview"><journey-scene :scene="place" :weather="state.weather" /></div><recipe-book :recipes="placeRecipes" :places="places" :foods="inventory.foods" :tools="inventory.tools" :souvenirs="inventory.souvenirs" :cards="cards" :compact="true" @prepare="prepareRecipe" @open="open" /><section id="packing" class="packing panel"><div><span class="eyebrow">YOUR LITTLE BACKPACK</span><h2>给它装一点路上的安心。</h2><div class="pack-block"><h3>食物</h3><div class="pack-options"><button v-for="item in inventory.foods" :key="item.key" :class="{chosen:food===item.key}" :disabled="item.quantity<=0" @click="food=item.key"><span>{{item.icon}}</span><strong>{{item.name}}</strong><small>剩余 {{item.quantity}}</small></button></div></div><div class="pack-block"><h3>工具</h3><div class="pack-options tools"><button :class="{chosen:!tool}" @click="tool=''"><span>·</span><strong>不带工具</strong><small>轻装出发</small></button><button v-for="item in inventory.tools" :key="item.key" :class="{chosen:tool===item.key}" :disabled="item.quantity<=0" @click="tool=item.key"><span>{{item.icon}}</span><strong>{{item.name}}</strong><small>{{item.description}}</small></button></div></div></div><div class="depart-box"><div class="pairing-hint"><strong>{{pairing?'✧ '+pairing.title:'一场随心的小旅行'}}</strong><p>{{pairing?'归来必得主题明信片和「'+itemName(pairing.reward)+'」，也会带回当地纪念品。':'带回当地纪念品；换种食物或工具，也许能凑出手帐里的特殊搭配。'}}</p><p v-if="selectedFood?.quantity<=0">这份食物还没备好，先去小铺兑换。</p><button class="text-button" @click="page='garden'">去小铺补充食物 →</button></div><p>{{selectedFood?selectedFood.icon+' '+selectedFood.name+' 将放进背包':'背包里没有可带的食物'}}</p><button class="primary" :disabled="!canDepart" @click="depart">{{trip?'小动物还在旅行中':busy?'正在出发…':'出发去'+places[place].name+' ↗'}}</button><button v-if="inventory.daily.available" class="text-button" @click="claimDaily" :disabled="busy">领取今日饭团补给</button></div></section></main>
<main v-else-if="page==='garden'"><button class="text-button garden-back" @click="page='prepare'">← 返回旅行准备</button><garden-shop :garden="garden" :foods="inventory.foods" :now="now" :busy="busy" @plant="plant" @harvest="harvest" @buy="buy" /></main>
        <main v-else-if="page==='backpack'"><div class="page-heading"><div><span class="eyebrow">BACKPACK & GIFTS</span><h1>把小小收获放好。</h1><p>食物会在出发时消耗，工具会一直留在背包里。旅行带回的东西会进入礼物图鉴。</p></div><span class="edition">{{foodCount}} 份食物</span></div><section class="daily-strip"><div><span>{{inventory.daily.item.icon}}</span><strong>今日饭团补给</strong><small>{{inventory.daily.available?'还可以领取一份':'已经领取，明天再来'}}</small></div><button class="primary" :disabled="busy||!inventory.daily.available" @click="claimDaily">{{inventory.daily.available?'领取饭团':'已领取'}}</button></section><div class="inventory-grid"><section><div class="section-heading"><h2>食物 <span>FOOD</span></h2></div><div class="item-list"><article v-for="item in inventory.foods" :key="item.key" :class="['item-row',{empty:item.quantity<=0}]"><span>{{item.icon}}</span><div><strong>{{item.name}}</strong><small>{{item.description}}</small></div><b>× {{item.quantity}}</b></article></div></section><section><div class="section-heading"><h2>工具 <span>TOOLS</span></h2></div><div class="item-list"><article v-for="item in inventory.tools" :key="item.key" :class="['item-row',{empty:item.quantity<=0}]"><span>{{item.icon}}</span><div><strong>{{item.name}}</strong><small>{{item.description}}</small></div><b>{{item.quantity>0?'已拥有':'未获得'}}</b></article></div></section></div><section class="gift-panel panel"><div><span class="eyebrow">LEAVE A LITTLE GIFT</span><h2>给朋友的小动物留个纪念品。</h2><p v-if="!state.friends.length">朋友入住并领养动物后，就可以在这里送礼。</p><p v-else-if="!giftableSouvenirs.length">还没有可送出的纪念品。等下一次旅行回来，也许就有了。</p><template v-else><label for="gift-friend">送给</label><select id="gift-friend" v-model="giftTo"><option v-for="friend in state.friends" :value="friend.username">{{friend.username}} 的 {{friend.name}}</option></select><div class="gift-options"><button v-for="item in giftableSouvenirs" :key="item.key" :class="{chosen:giftItem===item.key}" @click="giftItem=item.key"><span>{{item.icon}}</span><strong>{{item.name}}</strong><small>拥有 {{item.quantity}}</small></button></div></template></div><button class="primary" :disabled="!canGift" @click="sendGift">{{busy?'正在送出…':'送出小礼物 ↗'}}</button></section><section class="gift-log" v-if="gifts.length"><div class="section-heading"><h2>最近赠礼 <span>GIFT LOG</span></h2></div><article v-for="gift in gifts" :key="gift.id"><time>{{clock(gift.created_at)}}</time><p><b>{{gift.item.icon}} {{gift.item.name}}</b> {{gift.direction==='sent'?'送给了 '+gift.to_username:'来自 '+gift.from_username}}</p></article></section><section class="souvenir-book"><div class="section-heading"><h2>礼物图鉴 <span>SOUVENIRS</span></h2></div><div class="souvenir-grid"><article v-for="item in inventory.souvenirs" :key="item.key" :class="{locked:!item.first_obtained_at}"><span>{{item.first_obtained_at?item.icon:'?'}}</span><strong>{{item.name}}</strong><small>{{item.first_obtained_at?'第一次获得：'+date(item.first_obtained_at):'尚未获得'}}</small><b>× {{item.quantity}}</b></article></div></section></main>
        <main v-else-if="page==='world'"><div class="page-heading"><div><span class="eyebrow">SOMEWHERE, TOGETHER</span><h1>原来，你也在这里。</h1><p>同一地点，重叠的旅程，就能留下共同回忆。世界每 10 秒更新一次。</p></div></div><div class="world-grid"><section class="panel"><h2>朋友的小动物</h2><p v-if="!state.friends.length">还没有其他小动物入住。朋友注册并领养动物后，就会出现在这里。</p><div class="friend" v-for="friend in state.friends" :key="friend.username"><span class="friend-emoji">{{animals[friend.kind]}}</span><div><strong>{{friend.name}}</strong><small>{{friend.username}}的小动物</small></div><span class="friend-status">{{friend.place?'正在'+places[friend.place].name:'在小屋休息'}}</span></div></section><section class="panel"><h2>这个世界的足迹</h2><p v-if="!state.events.length">第一段故事，等着大家写下。</p><article class="world-event" v-for="event in state.events" :key="event.id"><time>{{clock(event.created_at)}}</time><p>{{event.message}}</p></article></section></div></main>
        <main v-else><div class="page-heading"><div><span class="eyebrow">POSTCARDS & MEMORIES</span><h1>把远方，收进日常。</h1><p>共 {{cards.length}} 张明信片，每一张都是走过的时光。</p></div></div><details class="collection-book"><summary>搭配明信片手帐 · {{recipes.filter(r=>cards.some(c=>c.template_key==='combo:'+r.key)).length}} / {{recipes.length}} 已收藏</summary><recipe-book :recipes="recipes" :places="places" :foods="inventory.foods" :tools="inventory.tools" :souvenirs="inventory.souvenirs" :cards="cards" @prepare="prepareRecipe" @open="open" /></details><div v-if="cards.length" class="card-grid"><button v-for="card in cards" class="postcard" @click="open(card)"><div class="mini-scene" :class="card.place"><span>{{places[card.place].icon}}</span><b v-if="card.participants.length" class="companions"><span v-for="(p,i) in card.participants" :key="i">{{animals[p.kind]}}</span></b><b v-else>{{animals[card.animal]}}</b><i v-if="!card.opened">NEW</i></div><div class="card-meta"><strong>{{card.encounter_id?'同行 · ':''}}{{places[card.place].name}}</strong><span>{{date(card.created_at)}}</span></div><span v-if="card.title" class="card-theme">{{card.title}}</span><p class="card-quote">“{{card.message}}”</p><p class="card-gifts">{{rewardText(card)}}</p></button></div><section v-else class="collection-empty"><span>✉</span><h2>信箱里，装着对远方的期待。</h2><p>完成第一次旅行，就能收到属于你的明信片。</p><button class="primary" @click="page='prepare'">去看看世界 ↗</button></section></main>
      </template>
      <footer><span>✳ 小小远行</span><span>不赶路，只收集沿途的小幸福。</span><span>一个慢慢长大的小世界</span></footer>
      <div v-if="selected" class="modal-backdrop" @click.self="selected=null"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="postcard-title"><button class="close" @click="selected=null" aria-label="关闭明信片" autofocus>×</button><div class="mini-scene large" :class="selected.place"><span>{{places[selected.place].icon}}</span><b v-if="selected.participants.length" class="companions"><span v-for="(p,i) in selected.participants" :key="i">{{animals[p.kind]}}</span></b><b v-else>{{animals[selected.animal]}}</b><div class="stamp">小小远行<br>POSTCARD</div></div><div class="letter"><span class="eyebrow">A LITTLE NOTE FOR YOU</span><div v-if="selected.encounter_id" class="encounter-label">两只小动物，一段共同回忆</div><h2 id="postcard-title">{{selected.title || ('来自'+places[selected.place].name+'的问候')}}</h2><p>“{{selected.message}}”</p><p v-if="selected.combination" class="card-theme">搭配回忆：{{itemName(selected.combination.food)}} ＋ {{places[selected.place].name}}{{selected.combination.tool?' ＋ '+itemName(selected.combination.tool):''}}</p><div class="souvenir"><span>顺手带回：</span><b v-for="item in selected.rewards" :key="item.key">{{item.icon}} {{item.name}}</b><b v-if="!selected.rewards?.length">{{selected.gift}}</b></div><p v-if="selected.weather" class="weather-memory">{{selected.weather.icon}} 出发那天 · {{selected.weather.name}} · {{selected.weather.season.name}} · {{selected.weather.date}}</p><div class="signature">{{selected.name}} · {{date(selected.created_at)}}</div><small>已自动保存到你的明信片收藏</small></div></section></div>
    </div>`
}).mount('#app');
